### ISSUE TITLE
Bounty tracking

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [thiswillbeyourgithub/SleepTk_pinetime_sleep_tracker#15]
This issue is just to keep track of what's left to do before I release the bounty to @cyberneel

Here's the link to [my original message](https://github.com/InfiniTimeOrg/InfiniTime/discussions/1797#discussioncomment-10996046)

Also, I mentioned at some point an extra 10% of dollars because he was such a joy to work with.

# DONE:
- [X] gently raise to an awakened state via customizable gradually increasing vibrations
- [X] wakeup feeling fresh thanks to keeping track of sleep cycle
- [X] knowing more about my insomnia by knowing mid sleep how far into a cycle I'm into (+ a red display to avoid blue light)
- [X] wakeup without waking up my significant other
- [X] wake up thanks to snooze hell (it's easy to snooze for 3min but hard to stop, making sure you won't get back to sleep)

# TODOs:
- [x] Sometimes use "natural wake" mode to vibrate just a bit every few seconds. This wakes me up only if I had enough rest, otherwise I can sleep through it

### Implied:
- ~~[ ] no crash~~
    - *this one is not fullfilled but the app is already great and I think there's a decent chance someone will figure it out as the PR gets looked at so I'm not counting it.*
- [x] setting to set the number of push to stop the alarm

## Not counted but appreciated:
- [ ] a PR that has decent chances of getting merged
- [ ] HR tracking ~~and motion tracking~~ (part of @Koloss0 's bounty)

**Comment by Koloss0** [comment]
To clarify, I did **not** specify motion tracking in my bounty as I know that is not a reliable metric. I did specify HR tracking thosho since it seemed to be better, at least for determining sleep start and stop times, based on what some others were saying.

I'll re-state it in bullet point form for complete clarity.

For $56 CAD (~$40 USD):
- Heartrate tracking of some sort.
- Cycle calculating (based on a fixed cycle length).
- Gradual wake

For $20 CAD (~$14 USD)
- Nighttime stats screen (Similar to Sleeptk)

Footnotes:
- I recognize that HR tracking is a lot of work. My bounty does not specify whether the tracking should be viewable by the user, so I'll leave it up to the contributor. I'm also uncertain whether saving HR data may potentially sabotage the PR since recording and saving HR data might be counter to InfiniTime's goal of maintaining a smaller footprint. The HR sensor also isn't perfect either, it's given me bad readings many times before. Given these points, I am open to debate about whether HR tracking is worth pursuing.
- I didn't mention it in my bounty, but I think it could be useful to receive a "sleep score" based on the heart rate data as well (Could just be an average BMP), but that is up to the contributor to decide.
- I'll emphasize again that I'm willing to alter the requirements if I think it will benefit the project, so please explain your reasoning if you feel the criteria should be changed.

**Comment by cyberneel** [comment]
@Koloss0 I think your requirements seem fair since they take into account the difficulty and settle for start/stop time calculation to begin with.

I think the sleep score is an interesting idea, but is there an advantage to knowing that if it is just an average BPM? Maybe @thiswillbeyourgithub has thoughts on this since they have a medical background.

For the  NightTime states screen, could you tell me any additions you are looking for? This is the current state:
![image](https://github.com/user-attachments/assets/6ff865ab-db8a-4a7e-bed8-966155e99d07)

As for the other features, I already got gradual wake and cycle counting based on predefined cycle length working.

**Comment by cyberneel** [comment]
@thiswillbeyourgithub [Here](https://github.com/cyberneel/InfiniTime/releases/tag/1.0.6b7) is a release with Natural wake and pushes to stop added to settings.

**Comment by Koloss0** [comment]
> For the NightTime states screen, could you tell me any additions you are looking for? This is the current state:

That is already plenty enough for the $20 reward. Excellent work, mate.

**Comment by Koloss0** [comment]
A cool idea could be to display the current HR on the stats screen, but that's pushing it in terms of clutter. Very good stuff.

**Comment by cyberneel** [comment]
> A cool idea could be to display the current HR on the stats screen, but that's pushing it in terms of clutter. Very good stuff.

I had that a while back but removed it as it was based on a background HRM PR that wasn't ready for merging.

Also, I was thinking the Cycle counting and gradual wake can be moved to the other bounty, and the HR requirement can be in its own bounty as that's the only one requiring sensor data. What do you think?

**Comment by thiswillbeyourgithub** [comment]
> I think the sleep score is an interesting idea, but is there an advantage to knowing that if it is just an average BPM? Maybe @thiswillbeyourgithub has thoughts on this since they have a medical background

There's no sleep quality formula that I know of that's not just used to sell watches and software. I would say thay if we get HR and maybe motion synced to gadgetbridge then maybe we can aggregate user data and figure it out in the future. A good idea would be a screen that asks you on a scale 1-5 how good you think you slept 10 minutes after waking up. That would be fairly helpful to engineer our scoring system.

Anyway all that is much farther down the line.

**Comment by Koloss0** [comment]
I'm ready to give @cyberneel my dollars. They've gone above and beyond and they shouldn't wait any longer. I'm willing to offer them the full $76 CAD amount from my bounty for what they've achieved. @thiswillbeyourgithub If you're ready too, please contact me on Discord so we can combine it into one satisfying transaction.

**Comment by cyberneel** [comment]
@Koloss0 thank you! Were you able to test the latest version?

**Comment by Koloss0** [comment]
I've just started using it so I've only used it for one night. It seems to have worked when I tried it, though I'm a bit fuzzy on what all the settings mean. I just installed 1.0.6b8, and I'm already liking the new layout.

**Comment by cyberneel** [comment]
Yeah, I think the settings are a little confusing if not explained. I can write documentation that explains better later. The ideal situation is where the UI speaks for itself, but with the screen size and the nature of the app, that may not work.

The Wake modes are:
**PreWake:** There are Pre Wake vibrations leading up to the alarm
**Natural:** Instead of a normal alarm, there is a vibration every 30 seconds starting at the desired alarm time
**Both:** Combines both of those features

**Comment by thiswillbeyourgithub** [comment]
> They've gone above and beyond and they shouldn't wait any longer.

I totally agree, I was on the verge of paying but the fact that the alarm failed 2 days in a row made me wait a bit. In any case @cyberneel proved super great so yeah I'll pay and it will probably get fixed soon anyway so it does not feel justified to make them wait more I agree.

> I'm willing to offer them the full $76 CAD amount from my bounty for what they've achieved.

I'm short on time so maybe @cyberneel  kept track of that: I said 100$ +10% right? I can give you an extra 10 in advance for making the feature to send the start and stop data to gadget bridge if you pledge to **try to** do so. If you're not interested then just say so. This way I don't have to pay twice the payment fees which are probably high for just $10. As it's not part of the bounty I can't make you wait for it so that's why I offered to pay in advance I hope that's okay with you.

> @thiswillbeyourgithub If you're ready too, please contact me on Discord so we can combine it into one satisfying transaction

I don't really understand what this means and I'm not using discord anyway. I reached out to @cyberneel a while ago and already have his info to send the money.

>  I can write documentation that explains better later.

I recommend creating a markdown table with column "T-10min ; T ; T+?" to explain the timeline of vibrations.

@cyberneel I'll send an email right away to arrange the payment.

**Comment by Koloss0** [comment]
@thiswillbeyourgithub Apologies, I assumed you were on Discord. Email is fine, too. I prefer kolosso@pm.me. By "one satisfying transaction," I meant I could send you the $76 and you can send the full amount (your bounty included) to @cyberneel.

**Comment by thiswillbeyourgithub** [comment]
I have sent the appropriate amount to @cyberneel ! Can you confirm?

**Comment by cyberneel** [comment]
> I have sent the appropriate amount to @cyberneel ! Can you confirm?

Yup, I received it! Thanks so much!

**Comment by thiswillbeyourgithub** [comment]
So great! Don't hesitate to reach out if I can be of any assistance for the future of this project.

Btw, I have made this other nice app for waspos, it might be vastly simpler to port. If you think you can be interested in porting it do tell me! 

![Screenshot_20241212-231254_1](https://github.com/user-attachments/assets/58c47bf9-500d-4d1b-81fa-be3b88f74678)


https://github.com/wasp-os/wasp-os/pull/418/files

**Comment by cyberneel** [comment]
@thiswillbeyourgithub sounds cool!  It should be quite simpler. I'll see when I can start it.

**Comment by thiswillbeyourgithub** [comment]
I created a repo for it btw: https://github.com/thiswillbeyourgithub/Pomodoro-wasp-os

**Comment by cyberneel** [comment]
@thiswillbeyourgithub @Koloss0 [Here](https://github.com/cyberneel/InfiniTime/releases/tag/1.0.6b9) is a new release.

**Comment by cyberneel** [comment]
@Koloss0 @thiswillbeyourgithub [Here](https://github.com/cyberneel/InfiniTime/releases/tag/1.0.6b9) is the new release
